insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (1,'Truco','T',-1,-1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (2,'Quiero Re-Truco','T',-1,1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (3,'Quiero Vale Cuatro','T',-1,2);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (4,'Envido','E',-1,-1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (5,'Envido','E',-1,4);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (6,'Real Envido','E',-1,-1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (7,'Real Envido','E',-1,4);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (8,'Real Envido','E',-1,5);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (9,'Falta Envido','E',-1,-1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (10,'Falta Envido','E',-1,4);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (11,'Falta Envido','E',-1,5);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (12,'Falta Envido','E',-1,6);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (13,'Falta Envido','E',-1,7);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (14,'Falta Envido','E',-1,8);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (15,'Truco_NoQuerido','T',1,1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (16,'Quiero Re-Truco_NoQuerido','T',2,2);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (17,'Quiero Vale Cuatro_NoQuerido','T',3,3);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (18,'Envido_NoQuerido','E',1,4);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (19,'Envido_NoQuerido','E',2,5);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (20,'Real Envido_NoQuerido','E',1,6);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (21,'Real Envido_NoQuerido','E',2,7);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (22,'Real Envido_NoQuerido','E',4,8);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (23,'Falta Envido_NoQuerido','E',1,9);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (24,'Falta Envido_NoQuerido','E',2,10);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (25,'Falta Envido_NoQuerido','E',4,11);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (26,'Falta Envido_NoQuerido','E',3,12);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (27,'Falta Envido_NoQuerido','E',5,13);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (28,'Falta Envido_NoQuerido','E',7,14);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (29,'Truco_Querido','T',2,1);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (30,'Quiero Re-Truco_Querido','T',3,2);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (31,'Quiero Vale Cuatro_Querido','T',4,3);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (32,'Envido_Querido','E',2,4);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (33,'Envido_Querido','E',4,5);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (34,'Real Envido_Querido','E',3,6);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (35,'Real Envido_Querido','E',5,7);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (36,'Real Envido_Querido','E',7,8);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (37,'Falta Envido_Querido','E',0,9);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (38,'Falta Envido_Querido','E',0,10);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (39,'Falta Envido_Querido','E',0,11);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (40,'Falta Envido_Querido','E',0,12);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (41,'Falta Envido_Querido','E',0,13);
insert into tipo_envites ( idtipoEnvite , nombreEnvite, tipoEnvite, puntaje, enviteAnterior) values (42,'Falta Envido_Querido','E',0,14);
